name: build-upload-docs
on:
  release:
    types: [published]

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ./docs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build sphinx documentation
      working-directory: ./docs
      run: |
        make html
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OLOREN_AI }}"
        channelId: live
        projectId: oloren-ai
        target: docs