name: build-docker-containers
on:
  release:
    types: [published]

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push cpu
        id: docker_build_cpu
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: oloren/chemengine:cpu-nightly-${{github.run_number}}
          file: ./docker/Dockerfile.cpu
      - name: Build and push gpu
        id: docker_build_gpu
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: oloren/chemengine:gpu-nightly-${{github.run_number}}
          file: ./docker/Dockerfile.gpu